### ISSUE TITLE
An error occurred when calling the reset function. Emergency！！

### ISSUE THREAD

**Issue by Alvin-shao** [jr-robotics/robo-gym#76]
Hello, I used Ubuntu 18.04 a few days ago, and now I have installed an Ubuntu 20.04 system. However, the problems that occur on these two systems are the same, both of which are calling reset function errors.
![image](https://github.com/jr-robotics/robo-gym/assets/92195934/0e25d658-8f6c-4d10-a77f-691877433aaa)
I have no issues starting the service manager with commands on the terminal.

![image](https://github.com/jr-robotics/robo-gym/assets/92195934/0f26b059-9603-409e-a5c2-087a21920e0c)
There are no issues with installing robot gym, and there are no issues with compiling the workspace of the robot. I'm not sure where the problem lies. Can you help solve it? Thank you！！

**Comment by Alvin-shao** [comment]
@matteolucchi 
Can you help solve it? Thank you！！

**Comment by Alvin-shao** [comment]
在log里找到了这个错误，怎么解决？
![image](https://github.com/jr-robotics/robo-gym/assets/92195934/0c5773a3-05c3-43a6-b339-852280186ce7)

**Comment by Alvin-shao** [comment]
问题已解决，有需要知道怎么解决的可以加我qq201976802

**Comment by Rasoul-Zahedifar** [comment]
Hello there,

I am writing for this issue as I faced with it too, but could solve the problem. hopefully, it works for you. If you can run gym.make properly and get the message "Successfully Started Robot Server", but get error while calling env.reset, this is because you installed robogym correctly but the problem comes from gym.make (or specifically, comes from gym, not robogym). You should install the gym version which is compatible with robogym.  It is highly likely that you are using a newer version of gym. You may need to change to proper version by "pip install gym==0.18.3".

Good Luck

**Comment by Alvin-shao** [comment]
> 嗨，你好
> 
> 我也面临着这个问题，我正在为这个问题写作，但可以解决问题。希望它对您有用。如果您可以正确运行 gym.make 并收到消息“已成功启动机器人服务器”，但在调用 env.rereset 时出现错误，这是因为您正确安装了 robogym，但问题来自 gym.make（或者具体来说，来自健身房，而不是 robogym）。您应该安装与机器人健身房兼容的健身房版本。您很可能使用的是较新版本的健身房。您可能需要通过“pip install gym==0.18.3”更改为正确的版本。
> 
> 祝你好运

Thank you very much for your answer. I tried it and it was indeed a problem with the GYM version. It can now be fully run.
Good luck！

**Comment by jr-b-reiterer** [comment]
Clarification on gym version compatibility planned in the course of #73.
